/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package osproject.memory;

import java.util.ArrayList;
import java.util.Deque;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import osproject.MainFrame;
import osproject.ProcessControlBlock;

/**
 *
 * @author user
 */
public class MemoryStatusGui extends javax.swing.JFrame {

    JLabel[] processMemoryLabel = new JLabel[10];
    JLabel[] noOfPagesLabel = new JLabel[10];
    JLabel[] framelabel = new JLabel[10];
    JLabel[] frameIndex = new JLabel[10];
    JLabel[] LALabel = new JLabel[10];
    public ArrayList<Frame> framesList = new ArrayList<>();
    public static int LRUindex=0;

    int usedMemory = 0;
    int pagesize = 4;
    int counter = -1;
    int processCounter = 0;
    public static final int memorySize = 512;
    String pageReplacementInfo;

    Queue<ProcessControlBlock> processQueue = new LinkedList<ProcessControlBlock>();

    ArrayList<ProcessControlBlock> processList = new ArrayList<>();
    CreatePages pages;

    /**
     * Creates new form MemoryStatusGui
     */
    public MemoryStatusGui() {
        initComponents();
        InitalizeLabelsToArray();
        intiView();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pg1 = new javax.swing.JLabel();
        m4 = new javax.swing.JLabel();
        pg2 = new javax.swing.JLabel();
        m5 = new javax.swing.JLabel();
        pg3 = new javax.swing.JLabel();
        m6 = new javax.swing.JLabel();
        pg6 = new javax.swing.JLabel();
        m7 = new javax.swing.JLabel();
        pg7 = new javax.swing.JLabel();
        m8 = new javax.swing.JLabel();
        pg8 = new javax.swing.JLabel();
        m9 = new javax.swing.JLabel();
        pg9 = new javax.swing.JLabel();
        m10 = new javax.swing.JLabel();
        pg10 = new javax.swing.JLabel();
        pg4 = new javax.swing.JLabel();
        pg5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        m3 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        m1 = new javax.swing.JLabel();
        m2 = new javax.swing.JLabel();
        totalMemoryLabel = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        usedMemoryLabel = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        freeMemoryLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        fl1 = new javax.swing.JLabel();
        fl2 = new javax.swing.JLabel();
        fl4 = new javax.swing.JLabel();
        fl5 = new javax.swing.JLabel();
        fl6 = new javax.swing.JLabel();
        fl7 = new javax.swing.JLabel();
        fl8 = new javax.swing.JLabel();
        fl9 = new javax.swing.JLabel();
        fl10 = new javax.swing.JLabel();
        fl3 = new javax.swing.JLabel();
        f1 = new javax.swing.JLabel();
        f2 = new javax.swing.JLabel();
        f3 = new javax.swing.JLabel();
        f4 = new javax.swing.JLabel();
        f5 = new javax.swing.JLabel();
        f6 = new javax.swing.JLabel();
        f7 = new javax.swing.JLabel();
        f8 = new javax.swing.JLabel();
        f9 = new javax.swing.JLabel();
        f10 = new javax.swing.JLabel();
        la1 = new javax.swing.JLabel();
        la2 = new javax.swing.JLabel();
        la4 = new javax.swing.JLabel();
        la3 = new javax.swing.JLabel();
        la5 = new javax.swing.JLabel();
        la7 = new javax.swing.JLabel();
        la6 = new javax.swing.JLabel();
        la8 = new javax.swing.JLabel();
        la9 = new javax.swing.JLabel();
        la10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cpuLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        pagehit = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        noOfFramesLabel = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Memory Management");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setText("Num of pages");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setText("Process");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel4.setText("Required Memory");

        pg1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        pg1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pg1.setText("Num of pages");
        pg1.setToolTipText("");

        m4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        m4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m4.setText("m4");

        pg2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        pg2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pg2.setText("Num of pages");

        m5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        m5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m5.setText("m5");

        pg3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        pg3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pg3.setText("Num of pages");

        m6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        m6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m6.setText("m6");

        pg6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        pg6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pg6.setText("Num of pages");

        m7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        m7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m7.setText("m7");

        pg7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        pg7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pg7.setText("Num of pages");

        m8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        m8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m8.setText("m8");

        pg8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        pg8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pg8.setText("Num of pages");

        m9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        m9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m9.setText("m9");

        pg9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        pg9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pg9.setText("Num of pages");

        m10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        m10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m10.setText("m10");

        pg10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        pg10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pg10.setText("Num of pages");

        pg4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        pg4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pg4.setText("Num of pages");

        pg5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        pg5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pg5.setText("Num of pages");

        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        m3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        m3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m3.setText("m3");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel31.setText("Process 9:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel28.setText("Process 8:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel22.setText("Process 6:");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel34.setText("Process 10:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel14.setText("Process 4:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel25.setText("Process 7:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel19.setText("Process 5:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setText("Process 2:");

        p1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        p1.setText("Process 1:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setText("Process 3:");

        m1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        m1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m1.setText("m1");

        m2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        m2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m2.setText("m2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel28)
                                .addComponent(jLabel31))
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel34)
                            .addComponent(p1))
                        .addGap(89, 89, 89)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pg2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pg1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(39, 39, 39))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(m10)
                                            .addComponent(m4)
                                            .addComponent(m6)
                                            .addComponent(m3)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(m7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(m8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(m9, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(m5)
                                            .addComponent(m1)
                                            .addComponent(m2))
                                        .addGap(161, 161, 161)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pg5)
                                            .addComponent(pg4)
                                            .addComponent(pg3)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pg7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(pg6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(pg8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(pg9, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(pg10)))
                                        .addGap(39, 39, 39))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(31, 31, 31))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(m1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(m2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(m3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(m4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(m5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(m6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(m7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(m8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(m9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(m10))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(pg1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pg2)
                            .addGap(7, 7, 7)
                            .addComponent(pg3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pg4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pg5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pg6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pg7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pg8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pg9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pg10))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel28)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel31)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel34)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        totalMemoryLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalMemoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalMemoryLabel.setText("0");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Total Memory");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Used Memory");

        usedMemoryLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usedMemoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        usedMemoryLabel.setText("0");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Free Memory");

        freeMemoryLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        freeMemoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        freeMemoryLabel.setText("0");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Create new Process");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Page size:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("0");

        jPanel3.setMaximumSize(new java.awt.Dimension(175, 234));
        jPanel3.setMinimumSize(new java.awt.Dimension(175, 234));

        fl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fl1.setText("Frame 1:");

        fl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fl2.setText("Frame 2:");

        fl4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fl4.setText("Frame 4:");

        fl5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fl5.setText("Frame 5:");

        fl6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fl6.setText("Frame 6:");

        fl7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fl7.setText("Frame 7:");

        fl8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fl8.setText("Frame 8:");

        fl9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fl9.setText("Frame 9:");

        fl10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fl10.setText("Frame 10:");

        fl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fl3.setText("Frame 3:");

        f1.setBackground(java.awt.Color.lightGray);
        f1.setText("Empty");

        f2.setText("Empty");

        f3.setText("Empty");

        f4.setText("Empty");

        f5.setText("Empty");

        f6.setText("Empty");

        f7.setText("Empty");

        f8.setText("Empty");

        f9.setText("Empty");

        f10.setText("Empty");

        la1.setText("jLabel6");

        la2.setText("jLabel6");

        la4.setText("jLabel6");

        la3.setText("jLabel6");

        la5.setText("jLabel6");

        la7.setText("jLabel6");

        la6.setText("jLabel6");

        la8.setText("jLabel6");

        la9.setText("jLabel6");

        la10.setText("jLabel6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(fl1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fl4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fl3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fl2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fl5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fl6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fl7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fl8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fl9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fl10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(la1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(la2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(la4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(la3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(la5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(la7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(la6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(la8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(la9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(la10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fl1)
                    .addComponent(f1)
                    .addComponent(la1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f2)
                    .addComponent(fl2)
                    .addComponent(la2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f3)
                    .addComponent(fl3)
                    .addComponent(la3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f4)
                    .addComponent(fl4)
                    .addComponent(la4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(f10)
                        .addComponent(la10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fl5)
                            .addComponent(f5)
                            .addComponent(la5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fl6)
                            .addComponent(f6)
                            .addComponent(la6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fl7)
                            .addComponent(f7)
                            .addComponent(la7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fl8)
                            .addComponent(f8)
                            .addComponent(la8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fl9)
                            .addComponent(f9)
                            .addComponent(la9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fl10)))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CPU :");

        cpuLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cpuLabel.setForeground(new java.awt.Color(255, 255, 255));
        cpuLabel.setText("0");

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LRU Algorithm");

        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Next Step");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pagehit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pagehit.setForeground(new java.awt.Color(255, 255, 102));
        pagehit.setText("page fault");

        jLabel10.setBackground(new java.awt.Color(255, 255, 204));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("No of Frames:");

        noOfFramesLabel.setBackground(new java.awt.Color(255, 255, 204));
        noOfFramesLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        noOfFramesLabel.setForeground(new java.awt.Color(255, 255, 255));
        noOfFramesLabel.setText("0");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Frame No#");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Logical address");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Page No#");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(439, 439, 439))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(totalMemoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usedMemoryLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(freeMemoryLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noOfFramesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cpuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pagehit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel26))))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(noOfFramesLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cpuLabel)
                                .addComponent(pagehit)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton2)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel7))
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel36)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(totalMemoryLabel)
                        .addGap(51, 51, 51)
                        .addComponent(usedMemoryLabel)
                        .addGap(47, 47, 47)
                        .addComponent(freeMemoryLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        createProcess();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    pages.NextStep();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemoryStatusGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemoryStatusGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemoryStatusGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemoryStatusGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemoryStatusGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel cpuLabel;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f10;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel f3;
    private javax.swing.JLabel f4;
    private javax.swing.JLabel f5;
    private javax.swing.JLabel f6;
    private javax.swing.JLabel f7;
    private javax.swing.JLabel f8;
    private javax.swing.JLabel f9;
    private javax.swing.JLabel fl1;
    private javax.swing.JLabel fl10;
    private javax.swing.JLabel fl2;
    private javax.swing.JLabel fl3;
    private javax.swing.JLabel fl4;
    private javax.swing.JLabel fl5;
    private javax.swing.JLabel fl6;
    private javax.swing.JLabel fl7;
    private javax.swing.JLabel fl8;
    private javax.swing.JLabel fl9;
    private javax.swing.JLabel freeMemoryLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel la1;
    private javax.swing.JLabel la10;
    private javax.swing.JLabel la2;
    private javax.swing.JLabel la3;
    private javax.swing.JLabel la4;
    private javax.swing.JLabel la5;
    private javax.swing.JLabel la6;
    private javax.swing.JLabel la7;
    private javax.swing.JLabel la8;
    private javax.swing.JLabel la9;
    private javax.swing.JLabel m1;
    private javax.swing.JLabel m10;
    private javax.swing.JLabel m2;
    private javax.swing.JLabel m3;
    private javax.swing.JLabel m4;
    private javax.swing.JLabel m5;
    private javax.swing.JLabel m6;
    private javax.swing.JLabel m7;
    private javax.swing.JLabel m8;
    private javax.swing.JLabel m9;
    private javax.swing.JLabel noOfFramesLabel;
    private javax.swing.JLabel p1;
    public javax.swing.JLabel pagehit;
    private javax.swing.JLabel pg1;
    private javax.swing.JLabel pg10;
    private javax.swing.JLabel pg2;
    private javax.swing.JLabel pg3;
    private javax.swing.JLabel pg4;
    private javax.swing.JLabel pg5;
    private javax.swing.JLabel pg6;
    private javax.swing.JLabel pg7;
    private javax.swing.JLabel pg8;
    private javax.swing.JLabel pg9;
    private javax.swing.JLabel totalMemoryLabel;
    private javax.swing.JLabel usedMemoryLabel;
    // End of variables declaration//GEN-END:variables

    public void createProcess() {
        int processMemorySize = 0;
        try {

            JTextField processSize = new JTextField(10);

            JPanel myPanel = new JPanel();
            myPanel.add(new JLabel("Process Size in KB:"));
            myPanel.add(processSize);

            int result = JOptionPane.showConfirmDialog(null, myPanel,
                    "Please Enter name and size of process", JOptionPane.OK_CANCEL_OPTION);
            
            if (result == JOptionPane.OK_OPTION) {
                
                processMemorySize = Integer.parseInt(processSize.getText());
                
                if (processMemorySize < memorySize && counter < 10) {
                    counter++;
                    ProcessControlBlock pcb = new ProcessControlBlock();
                    pcb.setProcessName("Process " + counter);
                    pcb.setMemoryRequired(processMemorySize);
                    pcb.setProcessId(counter);
                  
                    pages.ComputePages(pcb);

                    processList.add(pcb);
                } else {
                    String message;
                    if(counter>=10)
                        message="Process should not be more then 10";
                    else
                        message="process size should be less then memory size";
                    
                    JOptionPane.showMessageDialog(null, message, "Error", JOptionPane.ERROR_MESSAGE);
                }

            }
        } catch (NumberFormatException e) {

        }

    }

    public void createPages() {

    }

    void updateMemoryInfo() {
        
        usedMemoryLabel.setText("" + usedMemory);
        freeMemoryLabel.setText("" + (memorySize - usedMemory));
        pagehit.setText(pageReplacementInfo);
    }

    private void intiView() {
       
        noOfFramesLabel.setText("" + ((int) memorySize / pagesize));
        pagesize = MainFrame.PAGE_SIZE;
        updateMemoryInfo();
        totalMemoryLabel.setText(memorySize + "KB");
        jLabel7.setText("" + pagesize);
        pages = new CreatePages(this);
        System.out.print("pagesize" + pagesize);
    }

    private void InitalizeLabelsToArray() {
        processMemoryLabel[0] = m1;
        processMemoryLabel[1] = m2;
        processMemoryLabel[2] = m3;
        processMemoryLabel[3] = m4;
        processMemoryLabel[4] = m5;
        processMemoryLabel[5] = m6;
        processMemoryLabel[6] = m7;
        processMemoryLabel[7] = m8;
        processMemoryLabel[8] = m9;
        processMemoryLabel[9] = m10;

        noOfPagesLabel[0] = pg1;
        noOfPagesLabel[1] = pg2;
        noOfPagesLabel[2] = pg3;
        noOfPagesLabel[3] = pg4;
        noOfPagesLabel[4] = pg5;
        noOfPagesLabel[5] = pg6;
        noOfPagesLabel[6] = pg7;
        noOfPagesLabel[7] = pg8;
        noOfPagesLabel[8] = pg9;
        noOfPagesLabel[9] = pg10;

        framelabel[0] = fl1;
        framelabel[1] = fl2;
        framelabel[2] = fl3;
        framelabel[3] = fl4;
        framelabel[4] = fl5;
        framelabel[5] = fl6;
        framelabel[6] = fl7;
        framelabel[7] = fl8;
        framelabel[8] = fl9;
        framelabel[9] = fl10;

        frameIndex[0] = f1;
        frameIndex[1] = f2;
        frameIndex[2] = f3;
        frameIndex[3] = f4;
        frameIndex[4] = f5;
        frameIndex[5] = f6;
        frameIndex[6] = f7;
        frameIndex[7] = f8;
        frameIndex[8] = f9;
        frameIndex[9] = f10;
        
        
        //logical addresss 
        LALabel[0]=la1;
        LALabel[1]=la2;
        LALabel[2]=la3;
        LALabel[3]=la4;
        LALabel[4]=la5;
        LALabel[5]=la6;
        LALabel[6]=la7;
        LALabel[7]=la8;
        LALabel[8]=la9;
        LALabel[9]=la10;

    }

}
