/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package osproject;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Iterator;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author user
 */
public class ShowProcessStatus extends javax.swing.JFrame {

    /**
     * Creates new form ShowProcessStatus
     */
     SchedulingMethods method;
     public static int processCount;
     ArrayList<ProcessControlBlock> process;
     PriorityUtilQueues queues;
     ProcessQueues fcQueues;
     PriorityScheduling priorityScheduling;
     public static long totalExecutionTime=0;
     JLabel[] burstTimes = new JLabel[10], waitingTimes = new JLabel[10];
     JLabel[] priorities = new JLabel[10]; 
     ArrayList<Process> fcfs=new ArrayList<Process>();
     JProgressBar[] progressBars=new JProgressBar[10];
     
     public ShowProcessStatus() {
        initComponents();
        
        
        
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        alogrithm = new javax.swing.JLabel();
        cpu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        avgWaitingTime = new javax.swing.JLabel();
        avgBurstTime = new javax.swing.JLabel();
        totalExecutionTimeLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        readyQueue = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pr1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        bt1 = new javax.swing.JLabel();
        wt1 = new javax.swing.JLabel();
        pr2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        bt2 = new javax.swing.JLabel();
        wt2 = new javax.swing.JLabel();
        pr3 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jProgressBar3 = new javax.swing.JProgressBar();
        bt3 = new javax.swing.JLabel();
        wt3 = new javax.swing.JLabel();
        pr4 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jProgressBar4 = new javax.swing.JProgressBar();
        bt4 = new javax.swing.JLabel();
        wt4 = new javax.swing.JLabel();
        pr5 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jProgressBar5 = new javax.swing.JProgressBar();
        bt5 = new javax.swing.JLabel();
        wt5 = new javax.swing.JLabel();
        pr6 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jProgressBar6 = new javax.swing.JProgressBar();
        bt6 = new javax.swing.JLabel();
        wt6 = new javax.swing.JLabel();
        pr7 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jProgressBar7 = new javax.swing.JProgressBar();
        bt7 = new javax.swing.JLabel();
        wt7 = new javax.swing.JLabel();
        pr8 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jProgressBar8 = new javax.swing.JProgressBar();
        bt8 = new javax.swing.JLabel();
        wt8 = new javax.swing.JLabel();
        pr9 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jProgressBar9 = new javax.swing.JProgressBar();
        bt9 = new javax.swing.JLabel();
        wt9 = new javax.swing.JLabel();
        pr10 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jProgressBar10 = new javax.swing.JProgressBar();
        bt10 = new javax.swing.JLabel();
        wt10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        goodBye = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Algorithm");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CPU");

        alogrithm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alogrithm.setForeground(new java.awt.Color(255, 255, 255));
        alogrithm.setText("jLabel3");

        cpu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cpu.setForeground(new java.awt.Color(255, 255, 255));
        cpu.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Avg Waiting time :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Avg burst time :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Execution time :");

        avgWaitingTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        avgWaitingTime.setForeground(new java.awt.Color(255, 255, 255));
        avgWaitingTime.setText("0");

        avgBurstTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        avgBurstTime.setForeground(new java.awt.Color(255, 255, 255));
        avgBurstTime.setText("0");

        totalExecutionTimeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalExecutionTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalExecutionTimeLabel.setText("0");

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ready Queue");

        readyQueue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        readyQueue.setForeground(new java.awt.Color(255, 255, 255));
        readyQueue.setText("jLabel11");
        readyQueue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Priority");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Status bar");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Remaining Burst time");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Waiting Time");

        pr1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pr1.setForeground(new java.awt.Color(255, 255, 255));
        pr1.setText("0");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("P1 : ");

        jProgressBar1.setForeground(new java.awt.Color(255, 204, 51));

        bt1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt1.setForeground(new java.awt.Color(255, 255, 255));
        bt1.setText("0");

        wt1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wt1.setForeground(new java.awt.Color(255, 255, 255));
        wt1.setText("0");

        pr2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pr2.setForeground(new java.awt.Color(255, 255, 255));
        pr2.setText("0");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("P2 : ");

        jProgressBar2.setForeground(new java.awt.Color(255, 204, 51));

        bt2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt2.setForeground(new java.awt.Color(255, 255, 255));
        bt2.setText("0");

        wt2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wt2.setForeground(new java.awt.Color(255, 255, 255));
        wt2.setText("0");

        pr3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pr3.setForeground(new java.awt.Color(255, 255, 255));
        pr3.setText("0");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("P3 : ");

        jProgressBar3.setForeground(new java.awt.Color(255, 204, 51));

        bt3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt3.setForeground(new java.awt.Color(255, 255, 255));
        bt3.setText("0");

        wt3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wt3.setForeground(new java.awt.Color(255, 255, 255));
        wt3.setText("0");

        pr4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pr4.setForeground(new java.awt.Color(255, 255, 255));
        pr4.setText("0");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("P4 : ");

        jProgressBar4.setForeground(new java.awt.Color(255, 204, 51));

        bt4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt4.setForeground(new java.awt.Color(255, 255, 255));
        bt4.setText("0");

        wt4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wt4.setForeground(new java.awt.Color(255, 255, 255));
        wt4.setText("0");

        pr5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pr5.setForeground(new java.awt.Color(255, 255, 255));
        pr5.setText("0");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("P5 : ");

        jProgressBar5.setForeground(new java.awt.Color(255, 204, 51));

        bt5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt5.setForeground(new java.awt.Color(255, 255, 255));
        bt5.setText("0");

        wt5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wt5.setForeground(new java.awt.Color(255, 255, 255));
        wt5.setText("0");

        pr6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pr6.setForeground(new java.awt.Color(255, 255, 255));
        pr6.setText("0");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("P6 : ");

        jProgressBar6.setForeground(new java.awt.Color(255, 204, 51));

        bt6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt6.setForeground(new java.awt.Color(255, 255, 255));
        bt6.setText("0");

        wt6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wt6.setForeground(new java.awt.Color(255, 255, 255));
        wt6.setText("0");

        pr7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pr7.setForeground(new java.awt.Color(255, 255, 255));
        pr7.setText("0");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("P7 : ");

        jProgressBar7.setForeground(new java.awt.Color(255, 204, 51));

        bt7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt7.setForeground(new java.awt.Color(255, 255, 255));
        bt7.setText("0");

        wt7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wt7.setForeground(new java.awt.Color(255, 255, 255));
        wt7.setText("0");

        pr8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pr8.setForeground(new java.awt.Color(255, 255, 255));
        pr8.setText("0");

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("P8 : ");

        jProgressBar8.setForeground(new java.awt.Color(255, 204, 51));

        bt8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt8.setForeground(new java.awt.Color(255, 255, 255));
        bt8.setText("0");

        wt8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wt8.setForeground(new java.awt.Color(255, 255, 255));
        wt8.setText("0");

        pr9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pr9.setForeground(new java.awt.Color(255, 255, 255));
        pr9.setText("0");

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("P9 : ");

        jProgressBar9.setForeground(new java.awt.Color(255, 204, 51));

        bt9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt9.setForeground(new java.awt.Color(255, 255, 255));
        bt9.setText("0");

        wt9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wt9.setForeground(new java.awt.Color(255, 255, 255));
        wt9.setText("0");

        pr10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pr10.setForeground(new java.awt.Color(255, 255, 255));
        pr10.setText("0");

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("P10 : ");

        jProgressBar10.setForeground(new java.awt.Color(255, 204, 51));

        bt10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt10.setForeground(new java.awt.Color(255, 255, 255));
        bt10.setText("0");

        wt10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wt10.setForeground(new java.awt.Color(255, 255, 255));
        wt10.setText("0");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        goodBye.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        goodBye.setForeground(new java.awt.Color(255, 255, 255));
        goodBye.setText(" Good Byee ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addComponent(cpu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(alogrithm, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(readyQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(goodBye, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalExecutionTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(avgBurstTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avgWaitingTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pr8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jProgressBar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pr7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jProgressBar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pr6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jProgressBar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pr5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pr9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jProgressBar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pr10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jProgressBar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(pr3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(pr4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(99, 99, 99))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(pr2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pr1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 73, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(99, 99, 99))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(154, 154, 154)
                                        .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wt1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wt3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wt4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wt5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wt6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wt7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wt8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wt9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wt10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(alogrithm))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cpu))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(avgWaitingTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(avgBurstTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(totalExecutionTimeLabel))
                .addGap(78, 78, 78)
                .addComponent(goodBye, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(readyQueue)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(pr1))
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt1)
                        .addComponent(wt1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel22)
                                .addComponent(pr2))
                            .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bt2)
                                .addComponent(wt2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel26)
                                .addComponent(pr3))
                            .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bt3)
                                .addComponent(wt3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel30)
                                .addComponent(pr4))
                            .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(wt4)
                        .addComponent(bt4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel34)
                        .addComponent(pr5))
                    .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt5)
                        .addComponent(wt5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel38)
                        .addComponent(pr6))
                    .addComponent(jProgressBar6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt6)
                        .addComponent(wt6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel42)
                        .addComponent(pr7))
                    .addComponent(jProgressBar7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt7)
                        .addComponent(wt7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel46)
                        .addComponent(pr8))
                    .addComponent(jProgressBar8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt8)
                        .addComponent(wt8)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel50)
                        .addComponent(pr9))
                    .addComponent(jProgressBar9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt9)
                        .addComponent(wt9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel54)
                        .addComponent(pr10))
                    .addComponent(jProgressBar10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt10)
                        .addComponent(wt10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );

        alogrithm.getAccessibleContext().setAccessibleName("algorithm");
        cpu.getAccessibleContext().setAccessibleName("cpu");
        avgWaitingTime.getAccessibleContext().setAccessibleName("avgWaitingTime");
        avgBurstTime.getAccessibleContext().setAccessibleName("aveBurstTime");
        totalExecutionTimeLabel.getAccessibleContext().setAccessibleName("totalExecutionTime");
        readyQueue.getAccessibleContext().setAccessibleName("ReadyQueue");
        pr5.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param schedulingMethod
     * @param noOfProcess
     */
    public void setData(SchedulingMethods schedulingMethod,int noOfProcess){
        this.method=schedulingMethod;
        this.processCount=noOfProcess;
        this.setLocationRelativeTo(null);
        intiView();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowProcessStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowProcessStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowProcessStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowProcessStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowProcessStatus().setVisible(true);
            }
        });
    }
    
     public void intiView() {
         goodBye.setVisible(false);
         queues=new PriorityUtilQueues();
         fcQueues=new ProcessQueues();
         process=new ArrayList<ProcessControlBlock>();
         setVariableNames();
         alogrithm.setText(method.name());
         
         if(method==SchedulingMethods.PRIORITY){
             
             for(int i=0;i<processCount;i++){
                 ProcessControlBlock pcb=new ProcessControlBlock();
                 int j=i+1;
                 pcb.ProcessName=" P"+j;
                 pcb.processId=i+1;
                 int arriv=j+1;
                 pcb.arrivalTime=arriv;
                 pcb.priority=getRandomNumber(2,10);
                 pcb.burstTime=getRandomNumber(1,20);
                 
                 System.out.println("careated arrival time"+pcb.arrivalTime);
                 
                 progressBars[i].setMaximum(pcb.burstTime);
                 progressBars[i].setMinimum(0);
                 
                 
                 process.add(pcb);

             }
             
             
            
             ShowPriority();
              queues.readyQueue.addAll(process);
              NonPreemptivePriorityScheduling scheduler=new NonPreemptivePriorityScheduling();
              scheduler.setData(this);
              NonPreemptivePriorityScheduling.currentProcess= queues.readyQueue.poll();
              NonPreemptivePriorityScheduling.currentProcess.processStatus=ProcessState.RUNNING;
              
             
         }else if (method==SchedulingMethods.FCFS){
             alogrithm.setText(method.name());
             for(int i=0;i<processCount;i++){
                 int j=i+1;
                 Process obj=new Process();
                 obj.pcb.ProcessName="P"+j;
                 obj.pcb.parentProcessId=i;
                 obj.pcb.burstTime=getRandomNumber(1,20);
                 progressBars[i].setMaximum(obj.pcb.burstTime);
                 progressBars[i].setMinimum(0);
                 obj.pcb.arrivalTime=getRandomNumber(1,15);
                 fcfs.add(obj);
                
             }
             FCFS createFCFS=new FCFS();
             fcQueues.readyQueue.addAll(fcfs);
             FCFS.currentProcess=fcQueues.readyQueue.poll();
             FCFS.currentProcess.pcb.setProcessState(ProcessState.RUNNING);
             createFCFS.setMain(this);
         }
         
    }
     
     public void ShowPriority(){
         for(int i=0;i<processCount;i++){
             priorities[i].setText(String.valueOf(process.get(i).priority));
            
            
         
     }
     }
     
//     public void sortArrayList(){
//          Collections.sort(process, new Comparator<ProcessControlBlock>(){
//                 @Override
//                 public int compare(ProcessControlBlock o1, ProcessControlBlock o2) {
//                     return o1.arrivalTime-o2.arrivalTime;
//                 }
//                 
//             });
//     }
     
     
     public int getRandomNumber(int min, int max) {
    return (int) ((Math.random() * (max - min)) + min);
    }
     
     
     
     public void UpdateUI(){
         
         if(NonPreemptivePriorityScheduling.currentProcess!=null){
         ProcessControlBlock uiProcess=NonPreemptivePriorityScheduling.currentProcess;
         System.out.println("updateUI called");
         cpu.setText(uiProcess.ProcessName);
         int index=process.indexOf(uiProcess);
         waitingTimes[index].setText(""+uiProcess.waitingTime);
         int remainTime=uiProcess.burstTime-uiProcess.executed;
         burstTimes[index].setText(""+remainTime);
         progressBars[index].setValue(uiProcess.executed);
         
         }
         else{
         System.out.println("updateUI currentprocess NULL ");

         }
         StringBuilder builder=new StringBuilder();
         Iterator it=queues.readyQueue.iterator();
         while(it.hasNext()){
             ProcessControlBlock ready=(ProcessControlBlock) it.next();
             builder.append("|"+ready.ProcessName.toString());
         }
         readyQueue.setText(builder.toString());
     }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alogrithm;
    private javax.swing.JLabel avgBurstTime;
    private javax.swing.JLabel avgWaitingTime;
    private javax.swing.JLabel bt1;
    private javax.swing.JLabel bt10;
    private javax.swing.JLabel bt2;
    private javax.swing.JLabel bt3;
    private javax.swing.JLabel bt4;
    private javax.swing.JLabel bt5;
    private javax.swing.JLabel bt6;
    private javax.swing.JLabel bt7;
    private javax.swing.JLabel bt8;
    private javax.swing.JLabel bt9;
    private javax.swing.JLabel cpu;
    private javax.swing.JLabel goodBye;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar10;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JProgressBar jProgressBar6;
    private javax.swing.JProgressBar jProgressBar7;
    private javax.swing.JProgressBar jProgressBar8;
    private javax.swing.JProgressBar jProgressBar9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel pr1;
    private javax.swing.JLabel pr10;
    private javax.swing.JLabel pr2;
    private javax.swing.JLabel pr3;
    private javax.swing.JLabel pr4;
    private javax.swing.JLabel pr5;
    private javax.swing.JLabel pr6;
    private javax.swing.JLabel pr7;
    private javax.swing.JLabel pr8;
    private javax.swing.JLabel pr9;
    private javax.swing.JLabel readyQueue;
    private javax.swing.JLabel totalExecutionTimeLabel;
    private javax.swing.JLabel wt1;
    private javax.swing.JLabel wt10;
    private javax.swing.JLabel wt2;
    private javax.swing.JLabel wt3;
    private javax.swing.JLabel wt4;
    private javax.swing.JLabel wt5;
    private javax.swing.JLabel wt6;
    private javax.swing.JLabel wt7;
    private javax.swing.JLabel wt8;
    private javax.swing.JLabel wt9;
    // End of variables declaration//GEN-END:variables

    private void setVariableNames() {
        priorities[0]=pr1;
        priorities[1]=pr2;
        priorities[2]=pr3;
        priorities[3]=pr4;
        priorities[4]=pr5;
        priorities[5]=pr6;
        priorities[6]=pr7;
        priorities[7]=pr8;
        priorities[8]=pr9;
        priorities[9]=pr10;
        
        waitingTimes[0]=wt1;
        waitingTimes[1]=wt2;
        waitingTimes[2]=wt3;
        waitingTimes[3]=wt4;
        waitingTimes[4]=wt5;
        waitingTimes[5]=wt6;
        waitingTimes[6]=wt7;
        waitingTimes[7]=wt8;
        waitingTimes[8]=wt9;
        waitingTimes[9]=wt10;
        
        burstTimes[0]=bt1;
        burstTimes[1]=bt2;
        burstTimes[2]=bt3;
        burstTimes[3]=bt4;
        burstTimes[4]=bt5;
        burstTimes[5]=bt6;
        burstTimes[6]=bt7;
        burstTimes[7]=bt8;
        burstTimes[8]=bt9;
        burstTimes[9]=bt10;
        
        progressBars[0]=jProgressBar1;
        progressBars[1]=jProgressBar2;
        progressBars[2]=jProgressBar3;
        progressBars[3]=jProgressBar4;
        progressBars[4]=jProgressBar5;
        progressBars[5]=jProgressBar6;
        progressBars[6]=jProgressBar7;
        progressBars[7]=jProgressBar8;
        progressBars[8]=jProgressBar9;
        progressBars[9]=jProgressBar10;
        
        totalExecutionTime=(Long)System.nanoTime();
    } 

    public void showFinalResult(int Waiting,int burstTime,int totalTime){
         avgBurstTime.setText(String.valueOf(burstTime));
         avgWaitingTime.setText(String.valueOf(Waiting));
         totalExecutionTimeLabel.setText(String.valueOf(totalTime));
         goodBye.setVisible(true);
         cpu.setText("Free");
     }
    void FCupdateUI() {
       cpu.setText(FCFS.currentProcess.pcb.ProcessName);
       int index=fcfs.indexOf(FCFS.currentProcess);
       Process p=FCFS.currentProcess;
       int remain=(int) p.pcb.burstTime-p.pcb.executed;
       progressBars[index].setValue(p.pcb.executed);
       burstTimes[index].setText(""+remain);
       waitingTimes[index].setText(""+p.pcb.waitingTime);
       
       
       //ready queue
        StringBuilder builder=new StringBuilder();
         Iterator it=fcQueues.readyQueue.iterator();
         while(it.hasNext()){
             Process ready=(Process) it.next();
             builder.append("|"+ready.pcb.ProcessName.toString());
         }
         readyQueue.setText(builder.toString());
    }
    
   
    



   
}
